
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const GenerationScope = {
  API_ONLY: 'API_ONLY',
  UI_ONLY: 'UI_ONLY',
  E2E: 'E2E'
} as const

export type GenerationScope = (typeof GenerationScope)[keyof typeof GenerationScope]


export const UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN'
} as const

export type UserRole = (typeof UserRole)[keyof typeof UserRole]
